// Copyright 2026 The Parca Authors
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"math/big"
	"os"
	"path/filepath"
	"time"
)

// generateSelfSignedCert creates a self-signed TLS certificate for the webhook
// server. It writes tls.crt, tls.key, and ca.crt to the specified cert directory.
// This is used for development — in production, cert files are mounted via a
// Kubernetes secret generated by the TLS Job.
func generateSelfSignedCert() error {
	certDir := os.Getenv("PARCAGPU_WEBHOOK_CERT_DIR")
	if certDir == "" {
		certDir = "/certs"
	}

	if err := os.MkdirAll(certDir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", certDir, err)
	}

	priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return fmt.Errorf("generate key: %w", err)
	}

	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return fmt.Errorf("serial: %w", err)
	}

	tmpl := x509.Certificate{
		SerialNumber: serial,
		Subject: pkix.Name{
			Organization: []string{"parcagpu"},
			CommonName:   "parcagpu-webhook",
		},
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().Add(365 * 24 * time.Hour),
		KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageCertSign,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		BasicConstraintsValid: true,
		IsCA:                  true,
		DNSNames: []string{
			"parcagpu-webhook",
			"parcagpu-webhook.default",
			"parcagpu-webhook.default.svc",
			"parcagpu-webhook.default.svc.cluster.local",
		},
	}

	derBytes, err := x509.CreateCertificate(rand.Reader, &tmpl, &tmpl, &priv.PublicKey, priv)
	if err != nil {
		return fmt.Errorf("create cert: %w", err)
	}

	certPath := filepath.Join(certDir, "tls.crt")
	keyPath := filepath.Join(certDir, "tls.key")
	caPath := filepath.Join(certDir, "ca.crt")

	if err := writePEM(certPath, "CERTIFICATE", derBytes, 0o644); err != nil {
		return fmt.Errorf("write cert: %w", err)
	}

	keyBytes, err := x509.MarshalECPrivateKey(priv)
	if err != nil {
		return fmt.Errorf("marshal key: %w", err)
	}
	if err := writePEM(keyPath, "EC PRIVATE KEY", keyBytes, 0o600); err != nil {
		return fmt.Errorf("write key: %w", err)
	}

	// The CA bundle is the same self-signed cert.
	if err := writePEM(caPath, "CERTIFICATE", derBytes, 0o644); err != nil {
		return fmt.Errorf("write ca: %w", err)
	}

	return nil
}

func writePEM(path, blockType string, data []byte, mode os.FileMode) error {
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, mode)
	if err != nil {
		return err
	}
	defer f.Close()
	return pem.Encode(f, &pem.Block{Type: blockType, Bytes: data})
}
